### ISSUE TITLE
Windows user_data doesn't get populated

### ISSUE THREAD

**Issue by cranzy** [terraform-mirantis-modules/terraform-mirantis-provision-aws#1]
The line on https://github.com/terraform-mirantis-modules/terraform-mirantis-provision-aws/blob/332379aa723f7a7c757bbe862e4d6d84f0ce5cb1/modules/platform/ami.tf#L28
checks if  data.aws_ami.ami.platform == "windows" . However, for some reason when I try both "windows" or "Windows" .platform doesn't equal to either of them. Therefore, I'm suggesting to negate the statement like so:
`    { key : var.platform_key, ami : data.aws_ami.ami.id, user_data : data.aws_ami.ami.platform != "" ? local.user_data_windows : "" }
`
Info: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#platform

**Comment by james-nesbitt** [comment]
I think that this was resolved as incorrect.
